import { NextResponse } from 'next/server';
import { INDIAN_OCEAN_VESSELS } from '@/data/indianOceanMaritime';

export interface MaritimeVessel {
  id: string;
  mmsi: string;
  imo?: string;
  name: string;
  callsign: string;
  flag: string;
  flagCode: string;
  type: 'tanker' | 'cargo' | 'safari_boat' | 'rtl_ferry' | 'fishing_dhoni' | 'coast_guard' | 'naval_warship' | 'naval_support';
  typeName: string;
  coordinates: [number, number]; // [lng, lat]
  sog: number; // Speed Over Ground (knots)
  cog: number; // Course Over Ground (heading in degrees)
  navStatus: string;
  lengthMeters: number;
  beamMeters: number;
  draftMeters: number;
  origin: string;
  destination: string;
  eta: string;
  zone: string;
  hazardousCargo: boolean;
  history: [number, number][]; // Recent track coordinates
  inEEZ?: boolean;
  isMilitary?: boolean;
  /** SIMULATED_AIS = animated regional fleet; MODELED_OSINT = representative naval/regional picture */
  dataQuality?: 'SIMULATED_AIS' | 'MODELED_OSINT';
}

// Comprehensive Fleet Database covering Maldives EEZ and Surrounding International Sea Lanes (SLOC)
const BASE_VESSELS: MaritimeVessel[] = [
  // ─── 1. NORTHERN EEZ & EIGHT DEGREE CHANNEL (SLOC) ───
  {
    id: 'vessel-9293818',
    mmsi: '477281900',
    imo: '9293818',
    name: 'VLCC ARABIAN GLORY',
    callsign: 'VRMH8',
    flag: 'Saudi Arabia',
    flagCode: 'SA',
    type: 'tanker',
    typeName: 'Very Large Crude Carrier (VLCC)',
    coordinates: [72.45, 7.21],
    sog: 14.8,
    cog: 92,
    navStatus: 'Underway Using Engine',
    lengthMeters: 333,
    beamMeters: 60,
    draftMeters: 20.4,
    origin: 'Ras Tanura (SA)',
    destination: 'Singapore (SG)',
    eta: '2026-10-08 18:00',
    zone: 'Eight Degree Channel // Northern EEZ',
    hazardousCargo: true,
    history: [[71.2, 7.19], [71.8, 7.20], [72.45, 7.21]],
    inEEZ: true,
  },
  {
    id: 'vessel-9839211',
    mmsi: '636019283',
    imo: '9839211',
    name: 'MSC MEDITERRANEAN V',
    callsign: 'D5XY2',
    flag: 'Liberia',
    flagCode: 'LR',
    type: 'cargo',
    typeName: 'Ultra Large Container Vessel (24,000 TEU)',
    coordinates: [74.15, 7.24],
    sog: 18.2,
    cog: 271,
    navStatus: 'Underway Using Engine',
    lengthMeters: 399,
    beamMeters: 61,
    draftMeters: 16.2,
    origin: 'Port of Tanjung Pelepas (MY)',
    destination: 'Rotterdam (NL)',
    eta: '2026-10-14 06:00',
    zone: 'Eight Degree Channel // Northern EEZ',
    hazardousCargo: false,
    history: [[75.4, 7.26], [74.8, 7.25], [74.15, 7.24]],
    inEEZ: true,
  },
  {
    id: 'vessel-9412890',
    mmsi: '352981000',
    imo: '9412890',
    name: 'PACIFIC HORIZON LNG',
    callsign: '3FYK9',
    flag: 'Panama',
    flagCode: 'PA',
    type: 'tanker',
    typeName: 'LNG Carrier (174,000 cbm)',
    coordinates: [73.20, 7.18],
    sog: 16.5,
    cog: 90,
    navStatus: 'Underway Using Engine',
    lengthMeters: 299,
    beamMeters: 46,
    draftMeters: 11.8,
    origin: 'Ras Laffan (QA)',
    destination: 'Tokyo Bay (JP)',
    eta: '2026-10-10 12:00',
    zone: 'Eight Degree Channel // Northern EEZ',
    hazardousCargo: true,
    history: [[72.1, 7.17], [72.6, 7.17], [73.20, 7.18]],
    inEEZ: true,
  },
  {
    id: 'vessel-9811002',
    mmsi: '354921000',
    imo: '9811002',
    name: 'EVER GENIUS',
    callsign: 'BKAE9',
    flag: 'Panama',
    flagCode: 'PA',
    type: 'cargo',
    typeName: 'Evergreen G-Class Container (20,000 TEU)',
    coordinates: [75.60, 7.35],
    sog: 19.1,
    cog: 268,
    navStatus: 'Underway Using Engine',
    lengthMeters: 400,
    beamMeters: 59,
    draftMeters: 15.8,
    origin: 'Kaohsiung (TW)',
    destination: 'Suez Canal (EG)',
    eta: '2026-10-12 04:00',
    zone: 'Northern EEZ Outer Approach',
    hazardousCargo: false,
    history: [[76.4, 7.37], [76.0, 7.36], [75.60, 7.35]],
    inEEZ: false,
  },
  {
    id: 'vessel-9321884',
    mmsi: '228392000',
    imo: '9321884',
    name: 'TI OCEANIA',
    callsign: 'FNRY',
    flag: 'France',
    flagCode: 'FR',
    type: 'tanker',
    typeName: 'Ultra Large Crude Carrier (ULCC 441,000 DWT)',
    coordinates: [70.95, 7.15],
    sog: 13.9,
    cog: 92,
    navStatus: 'Underway Using Engine',
    lengthMeters: 380,
    beamMeters: 68,
    draftMeters: 24.5,
    origin: 'Basra Oil Terminal (IQ)',
    destination: 'Zhoushan (CN)',
    eta: '2026-10-15 08:00',
    zone: 'Northwestern EEZ Border',
    hazardousCargo: true,
    history: [[69.8, 7.12], [70.3, 7.14], [70.95, 7.15]],
    inEEZ: false,
  },
  {
    id: 'vessel-cgs-ghazee',
    mmsi: '455001004',
    name: 'CGS GHAZEE (MNDF COAST GUARD)',
    callsign: '8QCG4',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'coast_guard',
    typeName: 'Offshore Patrol Vessel (OPV 52m)',
    coordinates: [72.85, 7.65],
    sog: 20.4,
    cog: 80,
    navStatus: 'Maritime Sovereignty & EEZ Border Intercept',
    lengthMeters: 52,
    beamMeters: 8.5,
    draftMeters: 2.6,
    origin: 'Uligan Coast Guard Station',
    destination: 'Northern EEZ Demarcation Line',
    eta: '2026-10-06 02:00',
    zone: 'Northern EEZ Border Patrol',
    hazardousCargo: false,
    history: [[72.4, 7.55], [72.6, 7.60], [72.85, 7.65]],
    inEEZ: true,
  },

  // ─── 2. WESTERN EEZ FLANK (ARABIAN SEA / GULF OF ADEN TRANSIT) ───
  {
    id: 'vessel-9654123',
    mmsi: '257002000',
    imo: '9654123',
    name: 'FRONT ALTAIR',
    callsign: 'LAVB7',
    flag: 'Norway',
    flagCode: 'NO',
    type: 'tanker',
    typeName: 'Suezmax Crude Oil Tanker',
    coordinates: [70.40, 5.50],
    sog: 14.2,
    cog: 168,
    navStatus: 'Underway Using Engine',
    lengthMeters: 274,
    beamMeters: 48,
    draftMeters: 17.2,
    origin: 'Fujairah (AE)',
    destination: 'Cape Town (ZA)',
    eta: '2026-10-18 16:00',
    zone: 'Western EEZ Outer Corridor',
    hazardousCargo: true,
    history: [[70.2, 6.2], [70.3, 5.85], [70.40, 5.50]],
    inEEZ: false,
  },
  {
    id: 'vessel-9745881',
    mmsi: '211902000',
    imo: '9745881',
    name: 'AL JASRAH',
    callsign: 'DGBQ',
    flag: 'Germany',
    flagCode: 'DE',
    type: 'cargo',
    typeName: 'Hapag-Lloyd Container Ship (15,000 TEU)',
    coordinates: [70.65, 3.80],
    sog: 18.5,
    cog: 348,
    navStatus: 'Underway Using Engine',
    lengthMeters: 368,
    beamMeters: 51,
    draftMeters: 15.0,
    origin: 'Durban (ZA)',
    destination: 'Jebel Ali (AE)',
    eta: '2026-10-09 20:00',
    zone: 'Western EEZ International Waters',
    hazardousCargo: false,
    history: [[70.8, 3.1], [70.7, 3.45], [70.65, 3.80]],
    inEEZ: false,
  },
  {
    id: 'vessel-9612044',
    mmsi: '636018990',
    imo: '9612044',
    name: 'STI HERCULES',
    callsign: 'D5TL8',
    flag: 'Liberia',
    flagCode: 'LR',
    type: 'tanker',
    typeName: 'LR2 Product / Chemical Carrier',
    coordinates: [70.10, 2.20],
    sog: 13.8,
    cog: 162,
    navStatus: 'Underway Using Engine',
    lengthMeters: 250,
    beamMeters: 44,
    draftMeters: 14.5,
    origin: 'Ruwais (AE)',
    destination: 'Port Louis (MU)',
    eta: '2026-10-11 10:00',
    zone: 'Southwestern EEZ Boundary',
    hazardousCargo: true,
    history: [[69.9, 2.8], [70.0, 2.5], [70.10, 2.20]],
    inEEZ: false,
  },
  {
    id: 'vessel-cgs-thaarikh',
    mmsi: '455001006',
    name: 'CGS DHIVEHI THAARIKH',
    callsign: '8QCG6',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'coast_guard',
    typeName: 'Fast Patrol Vessel (FPV)',
    coordinates: [71.15, 3.75],
    sog: 24.0,
    cog: 180,
    navStatus: 'Underway Sovereignty Patrol',
    lengthMeters: 38,
    beamMeters: 7.2,
    draftMeters: 2.1,
    origin: 'MNDF Central Area HQ (L. Kadhdhoo)',
    destination: 'Western EEZ Anti-Illegal Fishing Recon',
    eta: '2026-10-06 06:00',
    zone: 'Western EEZ High Seas Border',
    hazardousCargo: false,
    history: [[71.15, 4.2], [71.15, 3.98], [71.15, 3.75]],
    inEEZ: true,
  },

  // ─── 3. EASTERN EEZ FLANK (BAY OF BENGAL / SRI LANKA / AUSTRALIA SLOC) ───
  {
    id: 'vessel-9806457',
    mmsi: '431008000',
    imo: '9806457',
    name: 'ONE APUS',
    callsign: '7KDF',
    flag: 'Japan',
    flagCode: 'JP',
    type: 'cargo',
    typeName: 'Ocean Network Express Magenta Container (14,000 TEU)',
    coordinates: [76.50, 5.60],
    sog: 19.8,
    cog: 218,
    navStatus: 'Underway Using Engine',
    lengthMeters: 364,
    beamMeters: 51,
    draftMeters: 15.5,
    origin: 'Colombo (LK)',
    destination: 'Fremantle (AU)',
    eta: '2026-10-13 14:00',
    zone: 'Eastern EEZ Maritime Corridor',
    hazardousCargo: false,
    history: [[76.8, 6.1], [76.65, 5.85], [76.50, 5.60]],
    inEEZ: false,
  },
  {
    id: 'vessel-9456128',
    mmsi: '564019000',
    imo: '9456128',
    name: 'BW GEMINI',
    callsign: '9V881',
    flag: 'Singapore',
    flagCode: 'SG',
    type: 'tanker',
    typeName: 'Very Large Gas Carrier (VLGC 84,000 cbm)',
    coordinates: [76.20, 3.80],
    sog: 15.7,
    cog: 38,
    navStatus: 'Underway Using Engine',
    lengthMeters: 226,
    beamMeters: 37,
    draftMeters: 11.2,
    origin: 'Dampier (AU)',
    destination: 'Mangalore (IN)',
    eta: '2026-10-07 18:00',
    zone: 'Eastern EEZ Outer Sector',
    hazardousCargo: true,
    history: [[76.0, 3.2], [76.1, 3.5], [76.20, 3.80]],
    inEEZ: false,
  },
  {
    id: 'vessel-9284910',
    mmsi: '477012900',
    imo: '9284910',
    name: 'PACIFIC BULKER',
    callsign: 'VRTL2',
    flag: 'Hong Kong',
    flagCode: 'HK',
    type: 'cargo',
    typeName: 'Capesize Bulk Carrier (180,000 DWT)',
    coordinates: [76.35, 1.90],
    sog: 12.8,
    cog: 215,
    navStatus: 'Underway Using Engine',
    lengthMeters: 292,
    beamMeters: 45,
    draftMeters: 17.8,
    origin: 'Paradip (IN)',
    destination: 'Port Hedland (AU)',
    eta: '2026-10-16 09:00',
    zone: 'Southeastern EEZ Outer Waters',
    hazardousCargo: false,
    history: [[76.6, 2.4], [76.48, 2.15], [76.35, 1.90]],
    inEEZ: false,
  },
  {
    id: 'vessel-tuna-chun7',
    mmsi: '416002891',
    name: 'CHUN YING NO.7',
    callsign: 'BK289',
    flag: 'Taiwan',
    flagCode: 'TW',
    type: 'fishing_dhoni',
    typeName: 'Deep-Sea Pelagic Tuna Longliner (68m)',
    coordinates: [75.90, 2.65],
    sog: 4.8,
    cog: 140,
    navStatus: 'Engaged in Longline Fishing',
    lengthMeters: 68,
    beamMeters: 11,
    draftMeters: 4.8,
    origin: 'Kaohsiung (TW)',
    destination: 'Indian Ocean High-Seas Fishing Zone',
    eta: '2026-10-25 12:00',
    zone: 'Eastern EEZ Outer Demarcation Line',
    hazardousCargo: false,
    history: [[75.8, 2.75], [75.85, 2.7], [75.90, 2.65]],
    inEEZ: true,
  },

  // ─── 4. ONE AND A HALF DEGREE CHANNEL (HUVADHOO KANDU / 1.5° N) ───
  {
    id: 'vessel-9778844',
    mmsi: '211832000',
    imo: '9778844',
    name: 'CMA CGM ANTOINE',
    callsign: 'FNRS',
    flag: 'France',
    flagCode: 'FR',
    type: 'cargo',
    typeName: 'Post-Panamax Container Ship (14,000 TEU)',
    coordinates: [73.80, 1.52],
    sog: 19.4,
    cog: 94,
    navStatus: 'Underway Using Engine',
    lengthMeters: 366,
    beamMeters: 48,
    draftMeters: 15.1,
    origin: 'Djibouti (DJ)',
    destination: 'Colombo (LK)',
    eta: '2026-10-06 04:00',
    zone: 'One and a Half Degree Channel',
    hazardousCargo: false,
    history: [[72.2, 1.49], [73.0, 1.50], [73.80, 1.52]],
    inEEZ: true,
  },
  {
    id: 'vessel-9632014',
    mmsi: '413289000',
    imo: '9632014',
    name: 'COSCO SHIPPING SOLAR',
    callsign: 'BOEU',
    flag: 'China',
    flagCode: 'CN',
    type: 'cargo',
    typeName: 'Mega Container Carrier (21,000 TEU)',
    coordinates: [72.30, 1.48],
    sog: 17.8,
    cog: 275,
    navStatus: 'Underway Using Engine',
    lengthMeters: 400,
    beamMeters: 59,
    draftMeters: 16.0,
    origin: 'Shanghai (CN)',
    destination: 'Jebel Ali (AE)',
    eta: '2026-10-08 10:30',
    zone: 'One and a Half Degree Channel',
    hazardousCargo: false,
    history: [[73.6, 1.51], [72.9, 1.49], [72.30, 1.48]],
    inEEZ: true,
  },
  {
    id: 'vessel-9759288',
    mmsi: '477019800',
    imo: '9759288',
    name: 'OOCL HONG KONG',
    callsign: 'VRMV9',
    flag: 'Hong Kong',
    flagCode: 'HK',
    type: 'cargo',
    typeName: 'Ultra Large Container Vessel (21,413 TEU)',
    coordinates: [74.65, 1.56],
    sog: 18.9,
    cog: 92,
    navStatus: 'Underway Using Engine',
    lengthMeters: 399,
    beamMeters: 58,
    draftMeters: 16.0,
    origin: 'Felixstowe (UK)',
    destination: 'Singapore (SG)',
    eta: '2026-10-09 14:00',
    zone: 'One and a Half Degree Channel Eastern Exit',
    hazardousCargo: false,
    history: [[73.9, 1.53], [74.3, 1.54], [74.65, 1.56]],
    inEEZ: true,
  },

  // ─── 5. EQUATORIAL CHANNEL & SOUTHERN EEZ (ADDU / CHAGOS CORRIDOR) ───
  {
    id: 'vessel-9304912',
    mmsi: '563012900',
    imo: '9304912',
    name: 'CAPE PIONEER',
    callsign: '9V891',
    flag: 'Singapore',
    flagCode: 'SG',
    type: 'cargo',
    typeName: 'Capesize Bulk Carrier (Ore/Coal)',
    coordinates: [73.10, -0.02],
    sog: 12.4,
    cog: 89,
    navStatus: 'Underway Using Engine',
    lengthMeters: 292,
    beamMeters: 45,
    draftMeters: 18.2,
    origin: 'Port Hedland (AU)',
    destination: 'Richards Bay (ZA)',
    eta: '2026-10-10 14:00',
    zone: 'Equatorial Channel',
    hazardousCargo: false,
    history: [[72.0, -0.04], [72.5, -0.03], [73.10, -0.02]],
    inEEZ: true,
  },
  {
    id: 'vessel-valemax-pacific',
    mmsi: '356012990',
    imo: '9575488',
    name: 'VALE PACIFIC',
    callsign: '3FTK8',
    flag: 'Panama',
    flagCode: 'PA',
    type: 'cargo',
    typeName: 'Very Large Ore Carrier (VLOC 400,000 DWT)',
    coordinates: [72.20, -2.40],
    sog: 13.5,
    cog: 102,
    navStatus: 'Underway Using Engine',
    lengthMeters: 362,
    beamMeters: 65,
    draftMeters: 23.0,
    origin: 'Tubarao (BR)',
    destination: 'Qingdao (CN)',
    eta: '2026-10-18 06:00',
    zone: 'Southern EEZ Border // Chagos Boundary',
    hazardousCargo: false,
    history: [[71.2, -2.55], [71.7, -2.48], [72.20, -2.40]],
    inEEZ: false,
  },
  {
    id: 'vessel-cgs-kaani',
    mmsi: '455001007',
    name: 'CGS KAANI',
    callsign: '8QCG7',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'coast_guard',
    typeName: 'Fast Interceptor Craft (FIC)',
    coordinates: [73.40, -2.15],
    sog: 26.5,
    cog: 270,
    navStatus: 'Southern Sovereignty & Anti-Poaching Patrol',
    lengthMeters: 30,
    beamMeters: 6.5,
    draftMeters: 1.8,
    origin: 'Addu Hithadhoo Naval Base',
    destination: 'Southern Maritime Boundary (Chagos)',
    eta: '2026-10-06 04:00',
    zone: 'Southern EEZ Border Patrol',
    hazardousCargo: false,
    history: [[73.9, -2.15], [73.65, -2.15], [73.40, -2.15]],
    inEEZ: true,
  },
  {
    id: 'vessel-cgs-ali',
    mmsi: '455001002',
    imo: '8990112',
    name: 'CGS SHAHEED ALI',
    callsign: '8QCG2',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'coast_guard',
    typeName: 'Fast Interceptor Craft (FIC)',
    coordinates: [73.08, -0.58],
    sog: 28.5,
    cog: 180,
    navStatus: 'Underway Sovereignty Patrol',
    lengthMeters: 28,
    beamMeters: 6,
    draftMeters: 1.6,
    origin: 'Addu Port Base',
    destination: 'Southern EEZ Anti-Poaching Patrol',
    eta: '2026-10-06 02:00',
    zone: 'Seenu / Equatorial Sector',
    hazardousCargo: false,
    history: [[73.09, -0.52], [73.08, -0.55], [73.08, -0.58]],
    inEEZ: true,
  },
  {
    id: 'vessel-tuna-reefer-ice',
    mmsi: '352001890',
    imo: '9128821',
    name: 'OCEAN BREEZE REEFER',
    callsign: '3FMN8',
    flag: 'Panama',
    flagCode: 'PA',
    type: 'cargo',
    typeName: 'Refrigerated Fish Carrier (120m)',
    coordinates: [74.50, -2.60],
    sog: 11.2,
    cog: 260,
    navStatus: 'Underway',
    lengthMeters: 120,
    beamMeters: 18,
    draftMeters: 6.8,
    origin: 'Seychelles (SC)',
    destination: 'Bangkok (TH)',
    eta: '2026-10-14 12:00',
    zone: 'Southern EEZ High Seas Corridor',
    hazardousCargo: false,
    history: [[75.2, -2.48], [74.85, -2.54], [74.50, -2.60]],
    inEEZ: false,
  },

  // ─── 6. MALÉ HARBOR, KAAFU ATOLL & INNER DOMESTIC FLEET ───
  {
    id: 'vessel-cgs-huravee',
    mmsi: '455001001',
    imo: '8990111',
    name: 'CGS HURAVEE (MNDF COAST GUARD)',
    callsign: '8QCG1',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'coast_guard',
    typeName: 'Offshore Patrol Vessel (OPV 46m)',
    coordinates: [73.58, 4.28],
    sog: 22.0,
    cog: 195,
    navStatus: 'Engaged in Maritime Sovereignty Patrol',
    lengthMeters: 46,
    beamMeters: 8,
    draftMeters: 2.8,
    origin: 'MNDF Coast Guard Base Hulhulé',
    destination: 'EEZ Northern Sector Intercept',
    eta: '2026-10-06 01:00',
    zone: 'Kaafu Atoll / North Malé Basin',
    hazardousCargo: false,
    history: [[73.54, 4.22], [73.56, 4.25], [73.58, 4.28]],
    inEEZ: true,
  },
  {
    id: 'vessel-cargo-city-male',
    mmsi: '455000088',
    imo: '9128372',
    name: 'MV CITY OF MALÉ',
    callsign: '8QCMV',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'cargo',
    typeName: 'Maldives State Shipping (MSS) General Feeder',
    coordinates: [73.495, 4.185],
    sog: 1.5,
    cog: 120,
    navStatus: 'Awaiting Berth at Male Commercial Harbor',
    lengthMeters: 140,
    beamMeters: 22,
    draftMeters: 7.8,
    origin: 'Tuticorin (IN)',
    destination: 'Malé Commercial Port (MV)',
    eta: '2026-10-05 22:00',
    zone: 'Malé Outer Anchorage',
    hazardousCargo: false,
    history: [[73.48, 4.16], [73.49, 4.175], [73.495, 4.185]],
    inEEZ: true,
  },
  {
    id: 'vessel-mss-galena',
    mmsi: '455000099',
    imo: '9428190',
    name: 'MSS GALENA',
    callsign: '8QMGN',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'cargo',
    typeName: 'MSS Container Feeder Vessel (850 TEU)',
    coordinates: [73.55, 3.95],
    sog: 12.4,
    cog: 350,
    navStatus: 'Underway Using Engine',
    lengthMeters: 132,
    beamMeters: 20,
    draftMeters: 6.9,
    origin: 'Colombo (LK)',
    destination: 'Malé Port (MV)',
    eta: '2026-10-06 05:30',
    zone: 'Vaadhoo Kandu // South Malé Approach',
    hazardousCargo: false,
    history: [[73.65, 3.7], [73.6, 3.82], [73.55, 3.95]],
    inEEZ: true,
  },
  {
    id: 'vessel-tanker-hulhumale',
    mmsi: '455000104',
    name: 'MT HULHUMALÉ TRADER',
    callsign: '8QHTR',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'tanker',
    typeName: 'Bunkering & Aviation Jet Fuel Barge',
    coordinates: [73.435, 4.175],
    sog: 0.0,
    cog: 0,
    navStatus: 'Moored at STO Fuel Berth',
    lengthMeters: 65,
    beamMeters: 12,
    draftMeters: 4.2,
    origin: 'Thilafushi Industrial Pier',
    destination: 'Velana Airport Sea Island Terminal',
    eta: '2026-10-05 18:00',
    zone: 'Thilafushi Industrial Basin',
    hazardousCargo: true,
    history: [[73.435, 4.175]],
    inEEZ: true,
  },
  {
    id: 'vessel-rtl-101',
    mmsi: '455120101',
    name: 'RTL EXPRESS SPEED 101',
    callsign: '8QR101',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'rtl_ferry',
    typeName: 'RTL High Speed Passenger Ferry',
    coordinates: [73.12, 6.78],
    sog: 31.2,
    cog: 215,
    navStatus: 'Scheduled Passenger Transit',
    lengthMeters: 19,
    beamMeters: 4.8,
    draftMeters: 1.1,
    origin: 'Dhidhdhoo (HA)',
    destination: 'Kulhudhuffushi Regional Terminal (HDh)',
    eta: '2026-10-05 22:15',
    zone: 'Haa Alif / Haa Dhaalu RTL Loop',
    hazardousCargo: false,
    history: [[73.15, 6.85], [73.13, 6.82], [73.12, 6.78]],
    inEEZ: true,
  },
  {
    id: 'vessel-rtl-204',
    mmsi: '455120204',
    name: 'RTL ADDU-FUVAHMULAH FERRY',
    callsign: '8QR204',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'rtl_ferry',
    typeName: 'RTL Deep Sea Passenger Catamaran',
    coordinates: [73.28, -0.42],
    sog: 28.0,
    cog: 350,
    navStatus: 'Underway Passenger Transit',
    lengthMeters: 24,
    beamMeters: 6.2,
    draftMeters: 1.4,
    origin: 'Hulhumeedhoo (S)',
    destination: 'Fuvahmulah Harbor (Gn)',
    eta: '2026-10-05 22:40',
    zone: 'Equatorial Ocean Channel',
    hazardousCargo: false,
    history: [[73.18, -0.55], [73.22, -0.49], [73.28, -0.42]],
    inEEZ: true,
  },
  {
    id: 'vessel-safari-scubaspa',
    mmsi: '455200389',
    name: 'MY SCUBASPA YING',
    callsign: '8QSCU',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'safari_boat',
    typeName: 'Luxury Liveaboard Cruiser (50m)',
    coordinates: [73.08, 5.14],
    sog: 8.5,
    cog: 45,
    navStatus: 'Cruising / Dive Safari',
    lengthMeters: 50,
    beamMeters: 11,
    draftMeters: 3.2,
    origin: 'Malé Harbor',
    destination: 'Hanifaru Bay Biosphere Reserve (Baa Atoll)',
    eta: '2026-10-06 07:30',
    zone: 'Baa Atoll Marine Biosphere',
    hazardousCargo: false,
    history: [[73.02, 5.06], [73.05, 5.10], [73.08, 5.14]],
    inEEZ: true,
  },
  {
    id: 'vessel-safari-blueforce',
    mmsi: '455200441',
    name: 'MV MALDIVES BLUE FORCE ONE',
    callsign: '8QBLU',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'safari_boat',
    typeName: 'Premium Diving Safari Yacht',
    coordinates: [72.88, 3.58],
    sog: 0.2,
    cog: 110,
    navStatus: 'Moored / Night Anchorage',
    lengthMeters: 42,
    beamMeters: 9,
    draftMeters: 2.7,
    origin: 'Rasdhoo Lagoon',
    destination: 'South Ari Whale Shark Marine Protected Area',
    eta: '2026-10-06 07:00',
    zone: 'Alif Dhaal / South Ari Atoll',
    hazardousCargo: false,
    history: [[72.87, 3.57], [72.88, 3.58]],
    inEEZ: true,
  },
  {
    id: 'vessel-dhoni-kaani',
    mmsi: '455301120',
    name: 'DHONI KAANI DHONKAMANA',
    callsign: '8QDHN1',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'fishing_dhoni',
    typeName: 'Maldivian Pole & Line Tuna Vessel',
    coordinates: [73.85, 3.20],
    sog: 11.2,
    cog: 290,
    navStatus: 'Returning from Yellowfin Grounds',
    lengthMeters: 32,
    beamMeters: 7.2,
    draftMeters: 2.4,
    origin: 'Outer EEZ High Seas',
    destination: 'MIFCO Fish Complex / Felivaru',
    eta: '2026-10-06 01:00',
    zone: 'Meemu Outer Ridge',
    hazardousCargo: false,
    history: [[74.05, 3.12], [73.95, 3.16], [73.85, 3.20]],
    inEEZ: true,
  },
  {
    id: 'vessel-dhoni-alivaree',
    mmsi: '455301145',
    name: 'DHONI ALIVAREE',
    callsign: '8QDHN5',
    flag: 'Maldives',
    flagCode: 'MV',
    type: 'fishing_dhoni',
    typeName: 'Skipjack Pole & Line Fishing Dhoni (35m)',
    coordinates: [73.90, 5.20],
    sog: 9.8,
    cog: 245,
    navStatus: 'Engaged in Fishing Operations',
    lengthMeters: 35,
    beamMeters: 7.8,
    draftMeters: 2.5,
    origin: 'Lhaviyani Atoll',
    destination: 'Felivaru Cannery',
    eta: '2026-10-06 03:30',
    zone: 'Lhaviyani / Eastern EEZ Edge',
    hazardousCargo: false,
    history: [[74.1, 5.28], [74.0, 5.24], [73.90, 5.20]],
    inEEZ: true,
  },
];

// Real-time kinematic AIS movement calculation
function calculateLivePositions(vessels: MaritimeVessel[]): MaritimeVessel[] {
  const now = new Date();
  const timeOffsetSeconds = now.getMinutes() * 60 + now.getSeconds();

  return vessels.map((v) => {
    if (v.sog < 1) {
      return v;
    }

    const speedDegPerSec = (v.sog * 1.852) / (111 * 3600);
    const rad = (v.cog * Math.PI) / 180;

    const idSeed = Array.from(v.id).reduce((acc, ch) => acc + ch.charCodeAt(0), 0);
    const driftCycleSec = (timeOffsetSeconds + (idSeed % 997) * 12) % 600;
    const deltaLat = Math.cos(rad) * speedDegPerSec * driftCycleSec * 2.5;
    const deltaLng = Math.sin(rad) * speedDegPerSec * driftCycleSec * 2.5;

    const currentLng = Number((v.coordinates[0] + deltaLng).toFixed(5));
    const currentLat = Number((v.coordinates[1] + deltaLat).toFixed(5));

    return {
      ...v,
      coordinates: [currentLng, currentLat] as [number, number],
      history: [
        ...v.history,
        [currentLng, currentLat] as [number, number],
      ].slice(-6) as [number, number][],
    };
  });
}

export async function GET() {
  try {
    const liveVessels = calculateLivePositions([
      ...BASE_VESSELS.map((v) => ({ ...v, dataQuality: v.dataQuality ?? ('SIMULATED_AIS' as const) })),
      ...INDIAN_OCEAN_VESSELS,
    ]);

    const stats = {
      total: liveVessels.length,
      insideEEZ: liveVessels.filter((v) => v.inEEZ).length,
      surroundingSLOC: liveVessels.filter((v) => !v.inEEZ).length,
      tankers: liveVessels.filter((v) => v.type === 'tanker').length,
      cargo: liveVessels.filter((v) => v.type === 'cargo').length,
      safariBoats: liveVessels.filter((v) => v.type === 'safari_boat').length,
      rtlFerries: liveVessels.filter((v) => v.type === 'rtl_ferry').length,
      coastGuard: liveVessels.filter((v) => v.type === 'coast_guard').length,
      fishingDhonis: liveVessels.filter((v) => v.type === 'fishing_dhoni').length,
      militaryVessels: liveVessels.filter((v) => v.isMilitary).length,
      indianOceanWide: liveVessels.filter((v) => v.dataQuality === 'MODELED_OSINT').length,
      chokepoints: {
        eightDegreeChannel: liveVessels.filter((v) => v.zone.includes('Eight Degree')).length,
        oneAndHalfDegreeChannel: liveVessels.filter((v) => v.zone.includes('One and a Half')).length,
        equatorialChannel: liveVessels.filter((v) => v.zone.includes('Equatorial')).length,
        maleHarborCongestion: 'HIGH (4 Vessels Outer Anchorage)',
      },
    };

    return NextResponse.json(
      {
        timestamp: new Date().toISOString(),
        source: 'MALDIVES_MARITIME_INTELLIGENCE_AIS',
        stats,
        vessels: liveVessels,
      },
      {
        headers: {
          'Cache-Control': 'public, s-maxage=10, stale-while-revalidate=20',
        },
      }
    );
  } catch (error: any) {
    return NextResponse.json(
      { error: 'Failed to retrieve maritime telemetry', message: error.message },
      { status: 500 }
    );
  }
}
